CREATE TABLE IF NOT EXISTS selic (
id  SERIAL PRIMARY KEY,
date DATE NOT NULL UNIQUE,
valor numeric(10,4) NOT NULL
);

CREATE TABLE IF NOT EXISTS cambio_usd(
id SERIAL PRIMARY KEY,
date DATE NOT NULL UNIQUE,
valor numeric(10,4) NOT NULL

CREATE TABLE IF NOT EXISTS ipca(
id SERIAL PRIMARY KEY,
date DATE NOT NULL UNIQUE,
VALOR numeric(10,4) NOT NULL
);



